login_system_project/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('users/register/',views.registration,name='register'),
    path('user-profile/',views.userProfile,name='user-profile'),
    path('user-profile-update/',views.userUpdate,name='user-profile-update')
]

login_system_project/login_system_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls',namespace='users')),
    path('registration/',include('account.urls',namespace='registration')),
    path('profile/user/',include('account.urls',namespace='profile')),
    path('profile/user/update/',include('account.urls',namespace='user-update')),
    path('login/user/',auth_views.LoginView.as_view(template_name='account/login.html'),name='login'),
    path('logout/user/',auth_views.LogoutView.as_view(template_name='account/logout.html'),name='logout'),
]

login_system_project/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('',views.index,name='index')
]

login_system_project/account/models.py
from django.db import models

# Create your models here.

login_system_project/users/models.py
from django.db import models

# Create your models here.

login_system_project/account/forms.py
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm

from django import forms


class userRegistrationForm(UserCreationForm):

    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    username = forms.CharField(max_length=30)
    email = forms.EmailField()

    class Meta:

        model = User

        fields = ['first_name','last_name','username','email','password1','password2']


class userUpdateForm(forms.ModelForm):

    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    username = forms.CharField(max_length=30)
    email = forms.EmailField()

    class Meta:

        model = User

        fields = ['first_name','last_name','username','email']

login_system_project/account/views.py
from django.shortcuts import render,redirect

from django.contrib.auth.models import User

from .forms import userRegistrationForm,userUpdateForm

from django.contrib import messages

from django.contrib.auth.decorators import login_required

def registration(request):

    form = userRegistrationForm()

    if request.method == 'POST':

        form = userRegistrationForm(request.POST)

        if form.is_valid():

            form.save()

            username = form.cleaned_data['username']

            messages.success(request, f'{username} has been created')

            return redirect('users:index')

    else:

        form = userRegistrationForm()


    return render(request,'account/registration-form.html',{'form':form})


@login_required
def userProfile(request):

    return render(request, 'account/user-profile.html')

@login_required
def userUpdate(request):

    user_form = userUpdateForm()

    if request.method == 'POST':

        user_form = userUpdateForm(request.POST,instance=request.user)

        if user_form.is_valid():

            user_form.save()

            username = user_form.cleaned_data['username']

            messages.success(request, f'{username} account has been updated')

            return redirect('profile:user-profile')

    else:

        user_form = userUpdateForm(instance=request.user)


    return render(request,'account/user-update-form.html',{'user_form':user_form})

login_system_project/users/views.py
from django.shortcuts import render

def index(request):

    return render(request,'users/index.html')

login_system_project/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'users/stylesheet/style.css' %}">
</head>

<body>

  <section id='header-section'>

    <header class='header'>

      <div class="container">

        <nav class="navbar navbar-expand-lg">
          <img class='logo' src="{% static 'users/images/logo.png' %}" alt="">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">


              {% if user.is_authenticated %}

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'profile:user-profile' %}">{{user.username}}</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user-update:user-profile-update' %}">Account</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>

              {% else %}

                <li class="nav-item active">
                  <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'registration:register' %}">Register</a>
                </li>

              {% endif %}


            </ul>

          </div>
        </nav>

      </div>

    </header>

  </section>

  <section id='main-section'>

    <main class='main'>

      <div class="container">
        {% if messages %}

        {% for message in messages %}

        <p class='alert alert-{{message.tags}}'>{{message}}</p>

        {% endfor %}

        {% endif %}
        {% block content %}

        {% endblock %}

      </div>

    </main>

  </section>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>

</html>

login_system_project/users/templates/users/index.html
{% extends 'users/base.html' %}

{% block content %}

  <div class="main-container">

    <div class="jumbotron jumbotron-fluid">

        <div class="hero-section text-center">

          <h1 class="display-4">Fluid jumbotron</h1>
          <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>

        </div>

    </div>

  </div>

{% endblock %}